package io.shelters

/**
 * In-memory parity with pilot seed data when `DB_URL` is unset.
 * Keeps sample data out of routing so routes stay thin.
 */
object ShelterSamples {
    val all: List<ShelterResponse> =
        listOf(
            ShelterResponse(
                id = "a0000001-0001-4001-8001-000000000001",
                name = "DOA dierenasiel",
                description =
                    "Dierenasiel voor honden, katten en konijnen in Nederland. " +
                        "Adoptie en zorg voor dieren die een tweede kans nodig hebben.",
                latitude = 52.3629026,
                longitude = 4.7845807,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://doa-dierenasiel.nl/help-mee/",
                imageUrl = "https://doa-dierenasiel.nl/wp-content/uploads/2022/08/logo-125.svg",
                donationUrl = "https://doa-dierenasiel.nl/help-mee/",
                city = "Amsterdam",
            ),
            ShelterResponse(
                id = "a0000002-0002-4002-8002-000000000002",
                name = "Reptielenopvang Zwanenburg",
                description =
                    "Opvang voor reptielen, amfibieën en geleedpotigen sinds 1983. " +
                        "Gelegen tussen Haarlem en Amsterdam.",
                latitude = 52.3794501,
                longitude = 4.7541101,
                species = listOf(ShelterSpecies.reptile, ShelterSpecies.amphibian),
                signupUrl = "https://reptielenopvang.nl/contact",
                imageUrl =
                    "https://reptileessentials.nl/cdn/shop/files/logo3.jpg?height=200&v=1753111538",
                donationUrl = "https://dierenlot.digicollect.nl/stichting-dierenhulpdienst-nederland",
                city = "Zwanenburg",
            ),
            ShelterResponse(
                id = "a0000003-0003-4003-8003-000000000003",
                name = "Stichting Dierenopvang Hengelo",
                description =
                    "Dierenopvang, pension en dierenambulance in de regio Hengelo e.o. " +
                        "Sinds 2003 opvang en herplaatsing van o.a. honden, katten en konijnen.",
                latitude = 52.2442726,
                longitude = 6.7645154,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenopvanghengelo.nl/onze-vrijwilligers/",
                imageUrl = "https://picsum.photos/seed/voluntail-hengelo/800/450",
                donationUrl = "https://dierenlot.digicollect.nl/stichting-dierenopvang-hengelo",
                city = "Hengelo",
            ),
            ShelterResponse(
                id = "a0000004-0004-4004-8004-000000000004",
                name = "Dierencentrum Achterhoek",
                description =
                    "Dierenasiel in de Achterhoek: opvang en zorg voor o.a. honden, katten, " +
                        "konijnen en knaagdieren voor meerdere omliggende gemeenten. Alleen op afspraak.",
                latitude = 51.9677498,
                longitude = 6.2669949,
                species =
                    listOf(
                        ShelterSpecies.dog,
                        ShelterSpecies.cat,
                        ShelterSpecies.rabbit,
                        ShelterSpecies.rodent,
                    ),
                signupUrl = "https://www.dierencentrumachterhoek.nl/over-ons/vrijwilligers",
                imageUrl = "https://picsum.photos/seed/voluntail-achterhoek/800/450",
                donationUrl = "https://www.dier.nu/beneficianten/stg-dierencentrum-achterhoek/",
                city = "Ruurlo",
            ),
            ShelterResponse(
                id = "a0000005-0005-4005-8005-000000000005",
                name = "Dierentehuis Arnhem en omstreken",
                description =
                    "Dierenasiel en dierenambulance voor negen gemeenten in de regio Arnhem. " +
                        "Zwerf- en afstandsdieren, quarantaine, hereniging en herplaatsing op afspraak.",
                latitude = 51.9892274,
                longitude = 5.9609043,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://dierentehuisarnhem.nl/contact/",
                imageUrl = "https://picsum.photos/seed/voluntail-arnhem/800/450",
                donationUrl = "https://dierentehuisarnhem.nl/doneer-hier/",
                city = "Arnhem",
            ),
            ShelterResponse(
                id = "a0000006-0006-4006-8006-000000000006",
                name = "Dierenopvang en Dierenambulance De Wissel",
                description =
                    "Dierenopvang sinds 1957 in Leeuwarden en wijde regio: honden, katten, " +
                        "konijnen en knaagdieren, plus dierenambulance in Leeuwarden.",
                latitude = 53.2097708,
                longitude = 5.8296983,
                species =
                    listOf(
                        ShelterSpecies.dog,
                        ShelterSpecies.cat,
                        ShelterSpecies.rabbit,
                        ShelterSpecies.rodent,
                    ),
                signupUrl = "https://www.dierenopvangdewissel.nl/steun-ons/word-vrijwilliger/",
                imageUrl = "https://picsum.photos/seed/voluntail-wissel/800/450",
                donationUrl = "https://www.dierenopvangdewissel.nl/steun-ons/word-donateur/",
                city = "Leeuwarden",
            ),
            ShelterResponse(
                id = "a0000007-0007-4007-8007-000000000007",
                name = "Dierentehuis 's-Hertogenbosch e.o.",
                description =
                    "Opvangcentrum met wildopvang voor inheemse wilde dieren naast herplaatsing van " +
                        "honden en katten en dierenambulance in 's-Hertogenbosch en omstreken.",
                latitude = 51.6915724,
                longitude = 5.3472806,
                species =
                    listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.wildlife),
                signupUrl = "https://dierentehuisdenbosch.nl/vrijwilligerswerk/",
                imageUrl = "https://picsum.photos/seed/voluntail-denbosch/800/450",
                donationUrl = "https://dierentehuisdenbosch.nl/steun-ons/doneren/",
                city = "'" + "s-Hertogenbosch",
            ),
            ShelterResponse(
                id = "a0000008-0008-4008-8008-000000000008",
                name = "Dierenopvangcentrum Rotterdam",
                description =
                    "Dierenopvang van De Dierenbescherming in Rotterdam voor o.a. honden en katten uit de stad; " +
                        "bezoek alleen op afspraak.",
                latitude = 51.9233004,
                longitude = 4.4384147,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat),
                signupUrl = "https://www.dierenbescherming.nl/in-actie-komen/vrijwilligerswerk/opvangwerk",
                imageUrl = "https://picsum.photos/seed/voluntail-rotterdam-db/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Rotterdam",
            ),
            ShelterResponse(
                id = "a0000009-0009-4009-8009-000000000009",
                name = "Dierenasiel Utrecht",
                description = "Onafhankelijk dierenasiel in Utrecht voor honden, katten en kleine huisdieren; op afspraak.",
                latitude = 52.0693076,
                longitude = 5.1468573,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenasielutrecht.nl/vrijwilligerswerk/",
                imageUrl = "https://picsum.photos/seed/voluntail-utrecht/800/450",
                donationUrl = "https://www.dierenasielutrecht.nl/word-vriend/",
                city = "Utrecht",
            ),
            ShelterResponse(
                id = "a000000a-000a-400a-800a-00000000000a",
                name = "Haags Dierencentrum",
                description = "Het Haags Dierencentrum opvang voor zwerfhonden en -katten en kliniek; alleen op afspraak.",
                latitude = 52.0359708,
                longitude = 4.2461312,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat),
                signupUrl = "https://haagsdierencentrum.nl/aanmelden-vrijwilliger/",
                imageUrl = "https://picsum.photos/seed/voluntail-den-haag/800/450",
                donationUrl = "https://haagsdierencentrum.nl/doneren/",
                city = "Den Haag",
            ),
            ShelterResponse(
                id = "a000000b-000b-400b-800b-00000000000b",
                name = "Dierenbeschermingscentrum Noord-Nederland",
                description = "Dierenbeschermingscentrum Noord-Nederland te Groningen voor opvang en herplaatsing uit de regio.",
                latitude = 53.2010673,
                longitude = 6.63028,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/dierenbeschermingscentrum-noord-nederland/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-groningen/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Groningen",
            ),
            ShelterResponse(
                id = "a000000c-000c-400c-800c-00000000000c",
                name = "DOC Breda",
                description = "Dierenopvangcentrum Breda voor honden, katten en veel kleindieren; werkgebied diverse gemeenten.",
                latitude = 51.6107983,
                longitude = 4.7728556,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://docbreda.nl/contact/",
                imageUrl = "https://picsum.photos/seed/voluntail-breda/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Breda",
            ),
            ShelterResponse(
                id = "a000000d-000d-400d-800d-00000000000d",
                name = "Dierenbeschermingscentrum Limburg",
                description = "Dierenbeschermingscentrum Limburg in Born: herplaatsing van honden, katten en kleindieren uit Limburg.",
                latitude = 51.0367665,
                longitude = 5.8358766,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/dierenbeschermingscentrum-limburg/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-limburg-born/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Born",
            ),
            ShelterResponse(
                id = "a000000e-000e-400e-800e-00000000000e",
                name = "Dierentehuis Zoetermeer",
                description = "Dierentehuis Zoetermeer met opvang voor honden en katten uit de stad en omstreken.",
                latitude = 52.0541521,
                longitude = 4.5242129,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat),
                signupUrl = "http://w.dierentehuiszoetermeer.nl/contactinfo.html",
                imageUrl = "https://picsum.photos/seed/voluntail-zoetermeer/800/450",
                donationUrl = "https://dierentehuiszoetermeer.nl/doneren/",
                city = "Zoetermeer",
            ),
            ShelterResponse(
                id = "a000000f-000f-400f-800f-00000000000f",
                name = "Zwols Dierenasiel",
                description = "Zwols Dierenasiel voor zwerfdieren uit Zwolle en omstreken.",
                latitude = 52.4853966,
                longitude = 6.1310268,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenasielzwolle.nl/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-zwolle/800/450",
                donationUrl = null,
                city = "Zwolle",
            ),
            ShelterResponse(
                id = "a0000010-0010-4010-8010-000000000010",
                name = "Dierenopvang Hart van Brabant (Tilburg)",
                description = "Dierenopvang Hart van Brabant (DOC Tilburg): opvang van zwerfdieren uit meerdere gemeenten.",
                latitude = 51.5940494,
                longitude = 5.0334516,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.doct.nl/vrijwilligers/",
                imageUrl = "https://picsum.photos/seed/voluntail-tilburg/800/450",
                donationUrl = null,
                city = "Tilburg",
            ),
            ShelterResponse(
                id = "a0000011-0011-4011-8011-000000000011",
                name = "Stichting ROZE",
                description = "Regionale Opvang Zwerfdieren Eindhoven: opvang voor de regio Eindhoven en omliggende gemeenten.",
                latitude = 51.4343223,
                longitude = 5.5136765,
                species =
                    listOf(
                        ShelterSpecies.dog,
                        ShelterSpecies.cat,
                        ShelterSpecies.rabbit,
                        ShelterSpecies.reptile,
                    ),
                signupUrl = "https://www.rozeindhoven.nl/contact/",
                imageUrl = "https://picsum.photos/seed/voluntail-eindhoven-roze/800/450",
                donationUrl = "https://www.rozeindhoven.nl/word-donateur/",
                city = "Eindhoven",
            ),
            ShelterResponse(
                id = "a0000012-0012-4012-8012-000000000012",
                name = "De Kuipershoek",
                description = "Dierenbescherming De Kuipershoek bij Klarenbeek: opvang voor gemeenten in Noord- en Oost-Gelderland.",
                latitude = 52.1798837,
                longitude = 5.9944967,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/de-kuipershoek/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-kuipershoek/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Klarenbeek",
            ),
            ShelterResponse(
                id = "a0000013-0013-4013-8013-000000000013",
                name = "Dierenbeschermingscentrum Amersfoort",
                description = "DBC Amersfoort voor opvang van katten, konijnen en kleindieren; onderdeel van De Dierenbescherming.",
                latitude = 52.1339997,
                longitude = 5.3655502,
                species =
                    listOf(ShelterSpecies.cat, ShelterSpecies.rabbit, ShelterSpecies.rodent),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/dierenbeschermingscentrum-amersfoort/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-amersfoort/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Amersfoort",
            ),
            ShelterResponse(
                id = "a0000014-0014-4014-8014-000000000014",
                name = "Dierentehuis Kennemerland",
                description = "Dierentehuis Kennemerland voor kustregio Noord-Holland.",
                latitude = 52.3843154,
                longitude = 4.5529392,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/dierentehuis-kennemerland/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-kennemerland/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Castricum",
            ),
            ShelterResponse(
                id = "a0000015-0015-4015-8015-000000000015",
                name = "Dierentehuis Stevenshage Leiden",
                description = "Stevenshage Leiden voor opvang en herplaatsing voor de regio Leiden.",
                latitude = 52.157614,
                longitude = 4.4473509,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenasielleiden.nl/contact/",
                imageUrl = "https://picsum.photos/seed/voluntail-leiden/800/450",
                donationUrl = "https://www.dierenasielleiden.nl/doneren/",
                city = "Leiden",
            ),
            ShelterResponse(
                id = "a0000016-0016-4016-8016-000000000016",
                name = "Dierenasiel de Swinge",
                description = "De Swinge Drachten: Fries dierenasiel onder De Dierenbescherming.",
                latitude = 53.0863467,
                longitude = 6.0758023,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/dierenasiel-de-swinge/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-drachten-swinge/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Drachten",
            ),
            ShelterResponse(
                id = "a0000017-0017-4017-8017-000000000017",
                name = "Dierenopvangcentrum Enschede",
                description = "DOC Enschede voor zwerfdieren uit Twente en omstreken.",
                latitude = 52.2038598,
                longitude = 6.8535269,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/dierenopvangcentrum-enschede/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-enschede/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Enschede",
            ),
            ShelterResponse(
                id = "a0000018-0018-4018-8018-000000000018",
                name = "Dierenopvangcentrum Gouda",
                description = "DOC Gouda voor zwerfhonden en -katten uit de regio.",
                latitude = 52.0331258,
                longitude = 4.6927113,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/dierenopvangcentrum-gouda/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-gouda/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Gouda",
            ),
            ShelterResponse(
                id = "a0000019-0019-4019-8019-000000000019",
                name = "Dierenopvangcentrum Spijkenisse",
                description = "DOC Spijkenisse voor zwerfdieren uit Voorne aan Zee en omliggende gemeenten.",
                latitude = 51.8623432,
                longitude = 4.2976039,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/dierenopvangcentrum-spijkenisse/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-spijkenisse/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Spijkenisse",
            ),
            ShelterResponse(
                id = "a000001a-001a-401a-801a-00000000001a",
                name = "Dierentehuis Alkmaar",
                description = "Dierentehuis Alkmaar (locatie Purmerend): tijdelijke vestiging onder De Dierenbescherming.",
                latitude = 52.5125259,
                longitude = 5.0021538,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/dierentehuis-alkmaar/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-alkmaar/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Purmerend",
            ),
            ShelterResponse(
                id = "a000001b-001b-401b-801b-00000000001b",
                name = "Dierenopvangcentrum Vlaardingen",
                description = "DOC Vlaardingen voor zwerfdieren en ambulance Zuid-Holland Zuid.",
                latitude = 51.9004792,
                longitude = 4.3058787,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/dierenopvangcentrum-vlaardingen/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-vlaardingen/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Vlaardingen",
            ),
            ShelterResponse(
                id = "a000001c-001c-401c-801c-00000000001c",
                name = "Dierenopvang Haarlemmermeer",
                description = "Stichting Dierenopvang Haarlemmermeer Hoofddorp onder De Dierenbescherming.",
                latitude = 52.3173681,
                longitude = 4.6969597,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat, ShelterSpecies.rabbit),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/dierenopvang-haarlemmermeer/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-hoofddorp/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Hoofddorp",
            ),
            ShelterResponse(
                id = "a000001d-001d-401d-801d-00000000001d",
                name = "Dierentehuis De Hof van Ede",
                description = "De Hof van Ede voor honden in Ede en kleindieren via Amersfoort.",
                latitude = 52.0353175,
                longitude = 5.7481906,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat),
                signupUrl = "https://www.dierenbescherming.nl/dierenasiel/dierentehuis-de-hof-van-ede/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-ede/800/450",
                donationUrl = "https://www.dierenbescherming.nl/doneren",
                city = "Ede",
            ),
            ShelterResponse(
                id = "a000001e-001e-401e-801e-00000000001e",
                name = "Dierenasiel Walcheren",
                description = "Dierenasiel Walcheren voor Walcheren en omstreken.",
                latitude = 51.4527536,
                longitude = 3.6034246,
                species = listOf(ShelterSpecies.dog, ShelterSpecies.cat),
                signupUrl = "https://www.dierenasielwalcheren.nl/contact",
                imageUrl = "https://picsum.photos/seed/voluntail-walcheren/800/450",
                donationUrl = null,
                city = "Middelburg",
            ),
        )
}
