-- Sample rows for local / QA (ids generated by default).
insert into public.shelters (
    name,
    description,
    latitude,
    longitude,
    registry_tag,
    species,
    signup_url,
    image_url,
    donation_url
)
values
    (
        'The Animal Line (sample)',
        'Dogs and cats from the Utrecht area. '
            || 'Small foster network for dogs and rabbits. '
            || 'V1: curated manually in Supabase; this row is stub data for API wiring only.',
        52.0907,
        5.1214,
        'DOA',
        '["dog","cat","rabbit"]'::jsonb,
        'https://example.com/signup',
        'https://picsum.photos/seed/voluntail-doa/800/450',
        'https://example.com/donate'
    ),
    (
        'Northern Reptile House (sample)',
        'Specialist care for reptiles and amphibians. '
            || 'Focus on housing and rehoming reptiles. '
            || 'Stub record for the ROZ track and map pins.',
        52.3676,
        4.9041,
        'ROZ',
        '["reptile","amphibian"]'::jsonb,
        null,
        'https://picsum.photos/seed/voluntail-roz/800/450',
        'https://example.com/donate-reptile'
    );
