-- Initial directory seed (8 shelters). Ids generated by default.
insert into public.shelters (
    name,
    description,
    latitude,
    longitude,
    species,
    signup_url,
    image_url,
    donation_url
)
values
    (
        'DOA dierenasiel',
        'Dierenasiel voor honden, katten en konijnen in Nederland. '
            || 'Adoptie en zorg voor dieren die een tweede kans nodig hebben.',
        52.3629026,
        4.7845807,
        '["dog","cat","rabbit"]'::jsonb,
        'https://doa-dierenasiel.nl/help-mee/',
        'https://doa-dierenasiel.nl/wp-content/uploads/2022/08/logo-125.svg',
        'https://doa-dierenasiel.nl/help-mee/'
    ),
    (
        'Reptielenopvang Zwanenburg',
        'Opvang voor reptielen, amfibieën en geleedpotigen sinds 1983. '
            || 'Gelegen tussen Haarlem en Amsterdam.',
        52.3794501,
        4.7541101,
        '["reptile"]'::jsonb,
        'https://reptielenopvang.nl/contact',
        'https://reptileessentials.nl/cdn/shop/files/logo3.jpg?height=200&v=1753111538',
        'https://dierenlot.digicollect.nl/stichting-dierenhulpdienst-nederland'
    ),
    (
        'Stichting Dierenopvang Hengelo',
        'Dierenopvang, pension en dierenambulance in de regio Hengelo e.o. ' ||
        'Sinds 2003 opvang en herplaatsing van o.a. honden, katten en konijnen.',
        52.2442726,
        6.7645154,
        '["dog","cat","rabbit"]'::jsonb,
        'https://www.dierenopvanghengelo.nl/onze-vrijwilligers/',
        'https://picsum.photos/seed/voluntail-hengelo/800/450',
        'https://dierenlot.digicollect.nl/stichting-dierenopvang-hengelo'
    ),
    (
        'Dierencentrum Achterhoek',
        'Dierenasiel in de Achterhoek: opvang en zorg voor o.a. honden, katten, ' ||
        'konijnen en knaagdieren voor meerdere omliggende gemeenten. Alleen op afspraak.',
        51.9677498,
        6.2669949,
        '["dog","cat","rabbit"]'::jsonb,
        'https://www.dierencentrumachterhoek.nl/over-ons/vrijwilligers',
        'https://picsum.photos/seed/voluntail-achterhoek/800/450',
        'https://www.dier.nu/beneficianten/stg-dierencentrum-achterhoek/'
    ),
    (
        'Dierentehuis Arnhem en omstreken',
        'Dierenasiel en dierenambulance voor negen gemeenten in de regio Arnhem. ' ||
        'Zwerf- en afstandsdieren, quarantaine, hereniging en herplaatsing op afspraak.',
        51.9892274,
        5.9609043,
        '["dog","cat","rabbit"]'::jsonb,
        'https://dierentehuisarnhem.nl/contact/',
        'https://picsum.photos/seed/voluntail-arnhem/800/450',
        'https://dierentehuisarnhem.nl/doneer-hier/'
    ),
    (
        'Dierenopvang en Dierenambulance De Wissel',
        'Dierenopvang sinds 1957 in Leeuwarden en wijde regio: honden, katten, ' ||
        'konijnen en knaagdieren, plus dierenambulance in Leeuwarden.',
        53.2097708,
        5.8296983,
        '["dog","cat","rabbit"]'::jsonb,
        'https://www.dierenopvangdewissel.nl/steun-ons/word-vrijwilliger/',
        'https://picsum.photos/seed/voluntail-wissel/800/450',
        'https://www.dierenopvangdewissel.nl/steun-ons/word-donateur/'
    ),
    (
        'Dierentehuis ''s-Hertogenbosch e.o.',
        'Opvangcentrum met wildopvang voor inheemse wilde dieren naast herplaatsing van ' ||
        'honden en katten en dierenambulance in ''s-Hertogenbosch en omstreken.',
        51.6915724,
        5.3472806,
        '["dog","cat","rabbit"]'::jsonb,
        'https://dierentehuisdenbosch.nl/vrijwilligerswerk/',
        'https://picsum.photos/seed/voluntail-denbosch/800/450',
        'https://dierentehuisdenbosch.nl/steun-ons/doneren/'
    ),
    (
        'Dierenopvangcentrum Rotterdam',
        'Dierenopvang van De Dierenbescherming in Rotterdam voor o.a. honden en katten uit de stad; ' ||
        'bezoek alleen op afspraak.',
        51.9233004,
        4.4384147,
        '["dog","cat","rabbit"]'::jsonb,
        'https://www.dierenbescherming.nl/in-actie-komen/vrijwilligerswerk/opvangwerk',
        'https://picsum.photos/seed/voluntail-rotterdam-db/800/450',
        'https://www.dierenbescherming.nl/doneren'
    );
